# Generated by Django 2.1.4 on 2019-08-06 10:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='articulospost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('cabecera', models.CharField(max_length=65, verbose_name='cabecera de google')),
                ('metacontenidos', models.CharField(max_length=150, verbose_name='descripción de página')),
                ('descripcion', ckeditor.fields.RichTextField(max_length=1500, verbose_name='Descripción ligera')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('bibliografia', models.CharField(max_length=1500, verbose_name='Bibliografía')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Miniatura')),
                ('encabezado1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Encabezado1')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Image1')),
                ('piedefigura1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pie de figura1')),
                ('encabezado2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Encabezado2')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Image2')),
                ('piedefigura2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pie de figura2')),
                ('encabezado3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Encabezado3')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Image3')),
                ('piedefigura3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pie de figura3')),
                ('encabezado4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Encabezado4')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Image4')),
                ('piedefigura4', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pie de figura4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('codigo', models.CharField(max_length=300, verbose_name='url')),
                ('encabezadovideo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Encabezado del vídeo')),
                ('video', models.CharField(blank=True, max_length=1000, null=True, verbose_name='url del vídeo')),
                ('descripcionvideo', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Descripción del vídeo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Arículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='categoriaarticulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de categoría')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.AddField(
            model_name='articulospost',
            name='categories',
            field=models.ManyToManyField(to='articulos.categoriaarticulos', verbose_name='Categorías'),
        ),
    ]
