# Generated by Django 2.1.4 on 2019-08-06 08:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cursosdivulgativospost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('title', models.CharField(max_length=65, verbose_name='Cabecera')),
                ('metacontent', models.CharField(max_length=150, verbose_name='Descripción en google')),
                ('descripcion', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Descripción ligera')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursosprofesionales', verbose_name='Miniatura')),
                ('precio', models.CharField(max_length=60, verbose_name='Precio sin rebajar')),
                ('descuento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Porcentaje descontado')),
                ('duracion', models.CharField(max_length=30, verbose_name='Duración del curso')),
                ('contenido', models.CharField(max_length=100, verbose_name='Contenido del curso')),
                ('explicacion', ckeditor.fields.RichTextField(max_length=10000, verbose_name='Explicación del curso')),
                ('requisitos', ckeditor.fields.RichTextField(max_length=100, verbose_name='Requisitos del curso')),
                ('titulovideo', models.CharField(max_length=100, verbose_name='Título del vídeo promocional')),
                ('videoprincipal', models.CharField(max_length=1000, verbose_name='url del vídeo promocional')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('codigo', models.CharField(max_length=300, verbose_name='codigo')),
                ('adquisicion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='link para comprar curso')),
                ('masinformacion', ckeditor.fields.RichTextField(blank=True, max_length=1500, null=True, verbose_name='Información extra del curso')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Curso divulgativo',
                'verbose_name_plural': 'Cursos divulgativos',
                'ordering': ['-created'],
            },
        ),
    ]
